worker_processes  auto;
events { worker_connections  1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;

  log_format ids_json escape=json
    '{ "time":"$time_local","ip":"$remote_addr","xff":"$http_x_forwarded_for",'
    '"method":"$request_method","uri":"$request_uri","args":"$args",'
    '"status":$status,"bytes":$body_bytes_sent,"req_len":$request_length,'
    '"req_time":$request_time,"up_time":"$upstream_response_time",'
    '"ua":"$http_user_agent","ref":"$http_referer","proto":"$server_protocol" }';

  access_log  /var/log/nginx/access.ids.log  ids_json;
  error_log   /var/log/nginx/error.log warn;

  sendfile        on;
  keepalive_timeout  65;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
