groups:
  - name: smartshield_metrics_rules
    interval: 5s
    rules:
            # CPU usage (%)
      - record: node:cpu_usage:ratio
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

      # Memory usage (bytes)
      - record: node:memory_usage:bytes
        expr: node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes

      # Disk usage (bytes used)
      - record: node:disk_usage:bytes
        expr: node_filesystem_size_bytes{fstype!~"tmpfs|overlay"} - node_filesystem_free_bytes{fstype!~"tmpfs|overlay"}

      # Network RX (bytes/sec)
      - record: node:network_rx:rate
        expr: rate(node_network_receive_bytes_total{device!~"lo"}[5m])

      # Network TX (bytes/sec)
      - record: node:network_tx:rate
        expr: rate(node_network_transmit_bytes_total{device!~"lo"}[5m])