global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"
  - "metrics_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']


remote_write:
  - url: "http://prometheus-kafka-adapter:8080/receive"
    write_relabel_configs:
      # Chỉ giữ lại metric cần thiết
      - source_labels: [__name__]
        regex: "node:cpu_usage:ratio|node:memory_usage:bytes|node:disk_usage:bytes|node:network_rx:rate|node:network_tx:rate"
        action: keep

# remote_write:
#   - url: "http://otel-collector:19291/api/v1/write"