version: "3.8"

services:
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2
    container_name: ids_fluentbit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - nginx_logs:/var/log/nginx:ro
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=nginx-logs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "2020:2020"   # Fluent Bit HTTP metrics
    depends_on:
      - kafka
      - redis
    networks:
      - monitoring_network

  prometheus-kafka-adapter:
    image: telefonica/prometheus-kafka-adapter:1.8.0
    container_name: ids_prometheus_kafka_adapter
    restart: always
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=raw_metrics
      - POLL_INTERVAL_MS=10000
    depends_on:
      - kafka
    networks:
      - monitoring_network

  metrics-flattener:
    build: ./metrics-flattener
    container_name: metrics-flattener
    depends_on:
      - kafka
    networks:
      - monitoring_network


  zookeeper:
    image: zookeeper
    container_name: ids_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - monitoring_network
      
  kafka:
    image: bitnami/kafka:3
    container_name: ids_kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - monitoring_network
  redis:
    image: redis:7
    container_name: ids_redis
    ports:
      - "6379:6379"

volumes:
  nginx_logs:
    external: true

networks:
  monitoring_network:
    external: true


