version: '3.8'

services:
  ddos-simulator:
    build: 
      context: ./apps/ddos-simulator
    container_name: ids_ddos_simulator
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "${SIMULATOR_HOST_PORT}:${SIMULATOR_CONTAINER_PORT}"
    networks:
      - ids-network
    restart: unless-stopped

networks:
  ids-network:
    external: true
